package components;

import java.util.Arrays;

// A gem represents all of the valid gems for a labyrinth game.
// ALL_VALID_GEM_NAMES represents all possible names for a gem.
// When creating a gem, the name must be in ALL_VALID_GEM_NAMES
// todo: Add tests
public class Gem {
  public final String name;
  public final static String[] ALL_VALID_GEM_NAMES = allValidGems();

  public Gem(String name) {
    if(!Arrays.asList(ALL_VALID_GEM_NAMES).contains(name)) {
      throw new IllegalArgumentException("Name not found.");
    }
    this.name = name;
  }

  private static String[] allValidGems() {
    return new String[]{"alexandrite-pear-shape",
        "alexandrite",
        "almandine-garnet",
        "amethyst",
        "ametrine",
        "ammolite",
        "apatite",
        "aplite",
        "apricot-square-radiant",
        "aquamarine",
        "australian-marquise",
        "aventurine",
        "azurite",
        "beryl",
        "black-obsidian",
        "black-onyx",
        "black-spinel-cushion",
        "blue-ceylon-sapphire",
        "blue-cushion",
        "blue-pear-shape",
        "blue-spinel-heart",
        "bulls-eye",
        "carnelian",
        "chrome-diopside",
        "chrysoberyl-cushion",
        "chrysolite",
        "citrine-checkerboard",
        "citrine",
        "clinohumite",
        "color-change-oval",
        "cordierite",
        "diamond",
        "dumortierite",
        "emerald",
        "fancy-spinel-marquise",
        "garnet",
        "golden-diamond-cut",
        "goldstone",
        "grandidierite",
        "gray-agate",
        "green-aventurine",
        "green-beryl-antique",
        "green-beryl",
        "green-princess-cut",
        "grossular-garnet",
        "hackmanite",
        "heliotrope",
        "hematite",
        "iolite-emerald-cut",
        "jasper",
        "jaspilite",
        "kunzite-oval",
        "kunzite",
        "labradorite",
        "lapis-lazuli",
        "lemon-quartz-briolette",
        "magnesite",
        "mexican-opal",
        "moonstone",
        "morganite-oval",
        "moss-agate",
        "orange-radiant",
        "padparadscha-oval",
        "padparadscha-sapphire",
        "peridot",
        "pink-emerald-cut",
        "pink-opal",
        "pink-round",
        "pink-spinel-cushion",
        "prasiolite",
        "prehnite",
        "purple-cabochon",
        "purple-oval",
        "purple-spinel-trillion",
        "purple-square-cushion",
        "raw-beryl",
        "raw-citrine",
        "red-diamond",
        "red-spinel-square-emerald-cut",
        "rhodonite",
        "rock-quartz",
        "rose-quartz",
        "ruby-diamond-profile",
        "ruby",
        "sphalerite",
        "spinel",
        "star-cabochon",
        "stilbite",
        "sunstone",
        "super-seven",
        "tanzanite-trillion",
        "tigers-eye",
        "tourmaline-laser-cut",
        "tourmaline",
        "unakite",
        "white-square",
        "yellow-baguette",
        "yellow-beryl-oval",
        "yellow-heart",
        "yellow-jasper",
        "zircon",
        "zoisite"};
  }
}
